### ISSUE TITLE
【Bug】Switching from different wordbooks will cause an exception

### ISSUE THREAD

**Issue by Sandu1213** [wordway/wordway-app#7]
## The problem
从不同的单词本里切换多次将高概率出现异常

## Environment

* OS Info: IOS 13.1.2
* Device Info: iPhone SE
* Model:  学习页

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，已存在账号且账号已登录
* Details:
1.选择添加多个单词本到学习里，然后在不同单词本里进行多次切换
2.重复上述操作多次，观察页面显示情况

* Expected Result:
1.页面显示正常，可以正常切换，学习
* Actual Result:
1.高概率出现错误页
 

## Attachments (eg:logs/video/screenshot)
![image](https://user-images.githubusercontent.com/21214285/66983091-56283580-f0ea-11e9-847a-02029f1f548c.png)

**Comment by lijy91** [comment]
问题已修复，请更新到 v1.1.0。
