### ISSUE TITLE
【Feature】suggest to optimize the continue study button description information

### ISSUE THREAD

**Issue by Sandu1213** [wordway/wordway-app#8]
### Details:
![image](https://user-images.githubusercontent.com/21214285/66984028-7e189880-f0ec-11e9-9c04-732f33f37fa0.png)

**Comment by lijy91** [comment]
@Sandu1213 感谢反馈，该优化已经列入优化计划

**Comment by lijy91** [comment]
功能已开发，请更新到 v1.1.0。
